#! /bin/sh

case $BUTTON in 
	1) st -e bpytop;;
	2)  ;;
	3) st -e nvim ~/suckless/status/components/disk ;;
esac

icon=""
disk=$(df -h | awk ' /nvme0n1p5/  {printf $3" | "$4}')

printf " %s %s " "$icon" "$disk"

